### ISSUE TITLE
No settings page available in Firefox ESR 45.8.0

### ISSUE THREAD

**Issue by nohamelin** [kafene/history-whitelist-webextension#1]
Hi,
I tried the add-on in a Linux system with Firefox ESR 45.8.0 and, after installing, no settings are visible or available for the add-on in the Add-ons Manager. The Browser Console shows the next message after install:

> SyntaxError: missing : after property id  ..........  background.js:67:44

It's using a clean Fx profile.

**Comment by kafene** [comment]
The minimum Firefox version is 50, due to use of the `history` API, which [gained full support in v50](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs#history).

Thank you for your report, I have added a minimum version to the manifest.json in commit a133387.
